useTodo 및 hook 연습
zelkovaria/useTodo-prac pull request #1
Opened 2024-03-14 13:51 UTC by zelkovaria

2024-03-16 22:44 UTC, ndaemy commented
일단 큰 리뷰부터 할게요

1. 이 repo 가 해당 목적으로만 쓰인다면, 위의 내용은 리뷰에 넣기보단 README.md 에 넣는게 좋을듯해요. 리뷰에서는 리뷰에 관한 얘기만 써있는게 좋습니다!
2. 왜.. package-lock.json 과 yarn.lock 이 같이 있는거죠..?

2024-03-16 22:54 UTC, ndaemy requested changes
수고하셨습니다. 하지만 한 번 더 손볼 곳들이 있어서 Request changes 남깁니다.

2024-03-16 22:54 UTC, ndaemy commented on src/RoutesContainer.js
이렇게 별도의 RoutesContainer 라는 파일을 만들거라면, 아래처럼 하는 것도 방법입니다
1. 현재 App.js 에 있는 내용들 -> index.js 로 보내고
2. 현재 RoutesContainer.js 에 있는 내용들 -> App.js 로 보내기

2024-03-16 22:54 UTC, ndaemy commented on src/TodosList.js
> +  return <>{!isLoading && data && <div>{data.title}</div>}</>;
이렇게 짜면 loading 중일때는 화면에 아무것도 보이지 않습니다.
유저의 환경에 따라 로딩이 길어질 수도 있는데, 이렇게 처리하면 로딩이 길어질 때 유저가 버그라고 오인지할 수도 있어요.
로딩중일 때는 로딩중이라고 보여주는 것이 더 나은 UX입니다.

2024-03-16 22:54 UTC, ndaemy commented on src/hooks/useTodo.js
> +  const [data, setData] = useState(undefined);
undefined 를 고의적으로 사용하는 것은 JavaScript 에서는 안티패턴입니다. [이 글](https://helloworldjavascript.net/pages/160-null-undefined.html)을 참고해보시지요.
따라서 여기서는 null을 사용하는 것이 더 적합합니다.

2024-03-16 22:54 UTC, ndaemy commented on src/hooks/useTodo.js
> +  const [error, setError] = useState(undefined);
위의 리뷰와 동일하게 undefined 는 사용하지 않는 것이 좋습니다.

2024-03-16 22:54 UTC, ndaemy commented on src/hooks/useTodo.js
> +        setError(undefined);
이미 error 객체가 undefined 인데 굳이 다시 set 할 필요는 없어보입니다.

2024-03-16 22:54 UTC, ndaemy commented on src/hooks/useTodo.js
> +        console.log(response.data);
hook 에서 불필요한 side effect 를 가지는 것도 안티패턴입니다.

2024-03-16 22:54 UTC, ndaemy commented on src/hooks/useTodo.js
> +        setData(undefined);
여기서 catch 로 넘어올 상황은 await 가 터졌을 때밖에 없는데, 그렇다면 data 가 이미 undefined 이므로 굳이 set 할 필요가 없습니다.

2024-03-16 22:54 UTC, ndaemy commented on src/TodosList.js
> +  const { data, isLoading, error } = useTodo(id);
error 객체는 가져왔는데 사용하지 않았습니다. error 객체도 사용하는 방향으로 코드를 한 번 작성해보시면 좋을듯합니다.

2024-03-17 14:01 UTC, zelkovaria commented on src/hooks/useTodo.js
> +  const [data, setData] = useState(undefined);
명시적으로 '없음'을 나타내는 경우를 구분할 수 있어야함에 따른 이유가 있네요! 덕분에 배웠습니당 ( ˃⍨˂̥̥ ) 🙇‍♀️

2024-03-17 14:02 UTC, zelkovaria commented on src/hooks/useTodo.js
> +  const [error, setError] = useState(undefined);
넴!! 감사합니다 👍🏻

2024-03-17 15:27 UTC, zelkovaria commented on src/hooks/useTodo.js
> +        console.log(response.data);
허걱 포함되는지 몰랐어요!! side effect에 대해 더 배워야 할 것 같네요!( ˃⍨˂̥̥ ) 감사합니당!! 🥺

2024-03-17 15:34 UTC, zelkovaria commented on src/hooks/useTodo.js
> +        setError(undefined);
불필요한 set 삭제하겠습니당 🔥

2024-03-17 15:48 UTC, zelkovaria commented on src/hooks/useTodo.js
> +        setData(undefined);
피드백 감사합니다 🙇‍♀️

2024-03-18 15:46 UTC, zelkovaria commented on src/TodosList.js
> +  return <>{!isLoading && data && <div>{data.title}</div>}</>;
좋은 피드백 감사합니다! 👍🏻

2024-03-18 16:04 UTC, zelkovaria commented on src/TodosList.js
> +  const { data, isLoading, error } = useTodo(id);
error에 따른 조건도 넣어보겠슴니당!! 🙇‍♀️

2024-03-18 19:54 UTC, ndaemy requested changes

2024-03-18 19:54 UTC, ndaemy commented on src/TodosList.js
> +  );
요것보다는 early return pattern 이 가독성도 더 좋을것 같고, 휴먼 에러도 더 방지할 수 있을 것 같아요!

2024-03-18 19:54 UTC, ndaemy commented on src/hooks/useTodo.js
> +  const [error, setError] = useState(null);
명시적인 빈 값을 null 로 넣은건 좋습니다
근데 만약 정의되지 않은것이니까 undefined 를 쓰고 싶다! 라고 하면 아예 인자를 안줘버리는 것도 방법이에요
useState 에 인자를 안넘기면 undefined 가 반환됩니다

2024-03-18 19:54 UTC, ndaemy commented on src/hooks/useTodo.js
> +    };
fetchData 함수는 one depth 위로 올려보면 조금 더 performance 에 도움이 될 것 같아요
왜냐하면 지금 이 위치라면 useEffect 가 터질 때마다 fetchData 함수가 새로 만들어지거든요

2024-03-19 03:07 UTC, zelkovaria commented on src/RoutesContainer.js
넵 🫡

2024-03-20 04:59 UTC, zelkovaria commented on src/TodosList.js
> +  );
if 조건문으로 다시 나눠봤습니다!! 확실히 더 나은 것 같아요 감사해요 🥺

2024-03-20 05:03 UTC, zelkovaria commented on src/hooks/useTodo.js
> +  const [error, setError] = useState(null);
정의되지 않은 상태인지라 말씀해주신 내용이 맞는 것 같아요! 피드백 감사합니다 👍🏻

2024-03-20 05:14 UTC, ndaemy requested changes

2024-03-20 05:14 UTC, ndaemy commented on src/TodosList.js
> +};
1. isLoading 이면 return 이라고 한 순간부터 `isLoading === false` 일 수밖에 없으므로, 이후 if 문에서 !isLoading 의 경우를 체크할 필요가 없어요. 아래처럼 수정하면 된다는 얘기입니다. error 의 경우도 마찬가지.

```suggestion
  if (isLoading) {
    return <div>로딩중</div>;
  }

  if (error) {
    return <div>에러 발생</div>;
  }

  if (data) {
    return <div>{data.title}</div>;
  }

  return <>기다려주세요</>;
};
```

2. 정상적인 return (데이터가 있는 경우) 를 가장 마지막에 두는 것이 일반적이에요. 그래야 맨 밑만 읽었을 때 정상 케이스를 확인할 수 있으니까요!

2024-03-20 06:33 UTC, zelkovaria commented on src/hooks/useTodo.js
> +    };
함수 자체를 useEffect 밖으로 빼서 one depth를 올리는 건 어떻게 생각하시나요?? 그러면 useEffect의 의존성 배열에는 Id, fetchData(id)로 추가해도 되지않을까 하는데,, 또 그렇게되면 컴포넌트 바깥에 함수를 정의하더라도 리렌더링이 될 때마다 함수는 결국 새롭게 만들어지는게 아닌가 하는 고민이 들어요 🥹

2024-03-20 06:49 UTC, zelkovaria commented on src/TodosList.js
> +};
왜 이 생각을 못했을가요,,,ㅎ 수정 완완입니당!! 감사합니다 🤧

2024-03-20 17:36 UTC, ndaemy requested changes

2024-03-20 17:36 UTC, ndaemy commented on src/TodosList.js
> +  return <>기다려주세요</>;
이 두 경우가 합쳐져야 할 듯
[swr 문서](https://swr.vercel.app/docs/getting-started#quick-start)를 보면 data fetching의 경우의 수는 보통 "loading", "ready", "error" 의 세가지라고 되어있으므로 if 문이 4개나 될 필요는 없어
그렇다면 어떻게 코드를 짜는게 이쁠지는 고민 고고 (일단 이렇게 4가지 경우가 나오는건 아님)

2024-03-25 12:41 UTC, zelkovaria commented on src/TodosList.js
> +  return <>기다려주세요</>;
수..수정해봤습니다 선생림!! 감사합니다..감사합니다..🥺

2024-03-26 12:48 UTC, ndaemy commented on src/hooks/useTodo.js
> +    };
그런 걸 방지하기 위해 useCallback 같은걸 쓰기도 하죠!
또 새로 공부할게 추가되겠군 📝

2024-03-26 12:50 UTC, ndaemy approved these changes
useTodo 의 약간의 리팩터링을 제외하고는 충분한듯해서 approve 합니다!

2024-03-26 13:46 UTC, merged